// GENERATED by @edgedb/generate v0.3.3

import type {Executor} from "edgedb";

export type GetApplicationArgs = {
  "host": string;
};

export type GetApplicationReturns = {
  "id": string;
  "client_id": string;
  "client_secret": string;
  "host": string;
} | null;

export async function getApplication(client: Executor, args: GetApplicationArgs): Promise<GetApplicationReturns> {
  return client.querySingle(`\
select Application{*}
filter .host = <str>$host
limit 1`, args);

}
