// GENERATED by @edgedb/generate v0.3.3

import type {Executor} from "edgedb";

export type InsertApplicationArgs = {
  "client_id": string;
  "client_secret": string;
  "host": string;
};

export type InsertApplicationReturns = {
  "id": string;
};

export async function insertApplication(client: Executor, args: InsertApplicationArgs): Promise<InsertApplicationReturns> {
  return client.queryRequiredSingle(`\
insert Application{
    client_id := <str>$client_id,
    client_secret := <str>$client_secret,
    host := <str>$host
}`, args);

}
